# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7290d404e5c68b7c7175f239741dc303"
application_url = "https://aerotex-widgets.vercel.app"
embedded = true
name = "Aerotex Widgets"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes,write_products,read_products"

[webhooks]
api_version = "2026-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://aerotex-widgets.vercel.app/webhooks"
  customer_data_request_url = "https://aerotex-widgets.vercel.app/webhooks"
  shop_deletion_url = "https://aerotex-widgets.vercel.app/webhooks"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://aerotex-widgets.vercel.app/auth/callback",
  "https://aerotex-widgets.vercel.app/auth/shopify/callback",
  "https://aerotex-widgets.vercel.app/api/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
