# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7290d404e5c68b7c7175f239741dc303"
name = "Aerotex Widgets"
application_url = "http://localhost:3000"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [ "http://localhost:3000/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
